modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="specialsguns"
version="1.0.0"
displayName="SpecialsGuns"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Wyu, MCreator"

[[dependencies.specialsguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




